### PR TITLE
WIP: bump 3.0.0

### LINKED ISSUE #24: Maybe wrong calculation
Hello, I have been using this app for a while and recently noticed something strange. If I put 72x72 image as @3x it generates 36x36 for @2x and 18x18 for @1x. I am using 2.6.1, and same was for version before. Maybe I am wrong but should it be 72 >> 48 >> 24? 

image 1x
image 2x
image 3x

By apple documentation it says:

72px × 72px (24pt × 24pt @3x) 
48px × 48px (24pt × 24pt @2x)

size @1x should be multiplied with 2 and 3. Thanks!

### PR DESCRIPTION
**Pull request by Kirow**
well...at first I wanted to change generated set of images to match xcode 10.1...but finished up with bunch of changes
#### Reworked models 
 - using Codable to work with json files 
 - added `Asset` protocol
 - `ContentsJSON` renamed `AssetCatalog`, using generics

```swift
protocol Asset {
    static func resourceName(forPlatform platform: String) -> String
    static func directory(named: String) -> String

    func save(_ image: [ImageOrientation: NSImage], aspect: AspectMode?, to url: URL) throws
}

extension Asset {
    static func resourceURL(forPlatform platform: String) throws -> URL { }
}

extension Asset where Self: Decodable {
    static func images(forPlatform platform: Platform, orientation: ImageOrientation? = nil) throws -> [Self] { }
}

class AssetCatalog<T: Codable & Asset>: Encodable {
   func save(_ image: [ImageOrientation: NSImage], named: String, toURL url: URL, aspect: AspectMode? = nil) throws { }
   func addPlatform(_ platform: Platform, orientation: ImageOrientation? = nil) throws { }
}

struct AppIcon: Codable, Asset { }
struct ImageSet: Codable, Asset { }
struct LaunchImage: Codable, Asset { }
```
usage:
```swift
let catalog = AssetCatalog<AppIcon>()
try catalog.addPlatform(.macOS)
try catalog.save([.none: image], named: name, toURL: url)
```
```swift
let catalog = AssetCatalog<LaunchImage>()
try catalog.addPlatform(.iPhone, orientation: .portrait)
try catalog.addPlatform(.iPhone, orientation: .landscape)
try catalog.save([
   .portrait: portraitInputImage
   .landscape: landscapeInputImage
], named: name, toURL: url, aspect: mode)
```
#### Changed json files structure
 - json files for `AppIcon` and `ImageSet` could be easily update. Just copy-paste `images` array from `Contents.json` generated from xcode
 - json files for `LaunchImage` image will require manual `size` (real pixel size) setting. (But I think it should be moved out of json file to avoid manual work during update. Need algorithm that can calculate sizes using original xcode `Contents.json` file)

#### Other changes
 - removed combined checkmark from AppIconViewController. (IMHO it is useless, always checked) Also it helps to keep interfaces cleaner.
- removed fix #24. It was not working with `.pdf` input. `NSImage.size` seems to be working fine now. I was not able to reproduce this issue.
- `autoreleasepool` usage to keep memory low during image generation

#### Thoughts:
 - need LaunchImage size calculation base on original `Contents.json`
 - image generation seems to be slow

Please review/discuss these changes.

### CODE REVIEW

**Comment by Kirow** [comment]
merged and adopted #12

**Comment by raphaelhanneken** [comment]
Wow. Amazing! Thank you very much for your efforts! I'll try to review the changes this evening. 👍

**Comment by raphaelhanneken** [comment]
I really love your changes - awesome work - and I would love to see this move forwards.

Regarding your thoughts:
* yes image generation is slow; But I don't know how to fix this. If you have any ideas, feel free to optimize 👍 
* I don't think I really understand what you mean by calculating the Launch Image size based on the original Contents.json, could you further elaborate this? An algorithm to calculate the image size could possibly be very complex to maintain when Apple decides to add and/or change the required image sizes, to me it seems easier just maintaining some sort of list.

I won't merge this pr for now, as I'm trying to always have a working master state.

**Comment by Kirow** [comment]
> yes image generation is slow; But I don't know how to fix this. If you have any ideas, feel free to optimize

Need to check if it is possible to cut some logic from `NSImageExtensions`, or maybe to reuse something during resizing. No plans to check this in near future. Guess if I will - it will be new PR

> I don't think I really understand what you mean by calculating the Launch Image size based on the original Contents.json, could you further elaborate this? An algorithm to calculate the image size could possibly be very complex to maintain when Apple decides to add and/or change the required image sizes, to me it seems easier just maintaining some sort of list.

(just for development workflow) Goal was to be able just to copy-paste `Contents.json` from empty assets generated by xcode. Works for `.appiconset` or `.stickersiconset`, because size and scale present in `Contents.json`. But for launch screen it is required to add `size` for each entity manually...pretty annoying. And I have no any good ideas how to get rid of it...

> I won't merge this pr for now, as I'm trying to always have a working master state.

Seems that I missed some renaming during last commit `¯\_(ツ)_/¯`. Fixed, must work now.
Overall, the app must work same way as before, except some changes:
 - removed combined checkmark
- added iMessage checkbox to AppIcon section
- minor changes to generated filenames and directories

**Comment by raphaelhanneken** [comment]
Thanks a lot! Great work! 👍

**Pull request merged**
